coverage:
  status:
    project:
      default:
        # basic
        target: 96
        threshold: 2%
        base: auto 
        flags: 
          - unit
        paths: 
          - "api"
       # advanced settings
        branches: 
          - master
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
