# Generated by Django 3.1.6 on 2021-02-21 20:58

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, primary_key=True, serialize=False, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator])),
                ('win_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rows', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(3, 'Min count 3')])),
                ('columns', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(3, 'Min count 3')])),
                ('winning_tick_count', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(3, 'Min count 3')])),
            ],
        ),
        migrations.CreateModel(
            name='SoloGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(blank=True, max_length=500)),
                ('turn', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3, 'Max 2 player')])),
                ('winner', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3, 'Max 2 player')])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rules', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.rules')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(blank=True, max_length=100)),
                ('turn', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3, 'Max 2 player')])),
                ('winner', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3, 'Max 2 player')])),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenger', to=settings.AUTH_USER_MODEL)),
                ('rules', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.rules')),
            ],
        ),
    ]
