name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
         python-version: 3.9 
      - name: Install dependencies
        run: ./install.sh
      - name: Run tests
        run: ./test.sh
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
        
  
  flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
         python-version: 3.9 
      - name: Install dependencies
        run: ./install.sh
      - name: Check code syntax
        run: flake8
      
